### ISSUE TITLE
自启动

### ISSUE THREAD

**Issue by heiheihaha2333** [bowjacon/zznet#3]
选取自启动时会直接后台关闭应用是不是正常现象

**Comment by heiheihaha2333** [comment]
而下次打开应用时开机自启按钮前没√

**Comment by bowjacon** [comment]
已改为修改注册表来实现自启动,如果没有奏效,.请尝试将快捷方式手动放入**启动**文件夹当中
ps:在地址输入框中输入**启动**并回车
![image](https://github.com/bowjacon/zznet/assets/99178447/bd960921-7e7a-4715-9c2a-3c0d5f271439)

**Comment by heiheihaha2333** [comment]
谢谢大佬

**Comment by heiheihaha2333** [comment]
网线连接时需要客户端，自动拨号不适用，会打开固定网页要求下载客户端。而开机计划任务打开网络客户端过一段时间会经常断连，大佬能不能看看有没有解决方法
